#!/bin/bash
# Move project and architecture markdown files to /specs subfolders

git mv COMPLETE_CHECKPOINT_DEC14.md specs/project/COMPLETE_CHECKPOINT_DEC14.md
git mv OPENTALENT_OPEN_SOURCE_STATUS.md specs/governance/OPENTALENT_OPEN_SOURCE_STATUS.md
git mv IMPLEMENTATION_QUICK_STATUS.md specs/project/IMPLEMENTATION_QUICK_STATUS.md
git mv SCOUT_AGENT_INTEGRATION_INDEX.md specs/architectural-specs/SCOUT_AGENT_INTEGRATION_INDEX.md
git mv QUICK_SUMMARY_ARCHITECTURE_DEC14.md specs/architectural-specs/QUICK_SUMMARY_ARCHITECTURE_DEC14.md
git mv PHASE2_IMPLEMENTATION_COMPLETE.md specs/project/PHASE2_IMPLEMENTATION_COMPLETE.md
git mv CUSTOM_MODEL_INTEGRATION_COMPLETE.md specs/architectural-specs/CUSTOM_MODEL_INTEGRATION_COMPLETE.md
git mv NOTIFICATION_SERVICE_IMPLEMENTATION_COMPLETE.md specs/architectural-specs/NOTIFICATION_SERVICE_IMPLEMENTATION_COMPLETE.md
git mv API_CATALOG_UPDATES_DEC16_FINAL.md specs/api-contracts/API_CATALOG_UPDATES_DEC16_FINAL.md
git mv API_CATALOG_UPDATES_DEC15_FINAL.md specs/api-contracts/API_CATALOG_UPDATES_DEC15_FINAL.md
git mv NOTIFICATION_SERVICE_FINAL_DELIVERY.md specs/architectural-specs/NOTIFICATION_SERVICE_FINAL_DELIVERY.md
git mv PHASE_9_DEMO_SCENARIOS.md specs/project/PHASE_9_DEMO_SCENARIOS.md
git mv PHASE_9_INDEX.md specs/project/PHASE_9_INDEX.md
git mv EFFICIENT_SOURCING_STRATEGY.md specs/requirements/EFFICIENT_SOURCING_STRATEGY.md
git mv DAY1-2_VERIFICATION_REPORT.md specs/project/DAY1-2_VERIFICATION_REPORT.md
git mv REAL_IMPLEMENTATION_DELIVERED.md specs/project/REAL_IMPLEMENTATION_DELIVERED.md
git mv SCHEMA_INTEGRATION_PHASE1_COMPLETE.md specs/architectural-specs/SCHEMA_INTEGRATION_PHASE1_COMPLETE.md
git mv OPENAPI_VERIFICATION_COMPLETE.md specs/api-contracts/OPENAPI_VERIFICATION_COMPLETE.md
git mv SCOUT_SERVICE_AGENT_INTEGRATION_CHECKLIST.md specs/architectural-specs/SCOUT_SERVICE_AGENT_INTEGRATION_CHECKLIST.md
git mv MICROSERVICES_MIGRATION_COMPLETE.md specs/migration/MICROSERVICES_MIGRATION_COMPLETE.md

echo "All moves complete. Run 'git status' to review and 'git commit -m \"Move first batch of markdown docs to /specs\"' to commit."
