"""Add initial system version record

Revision ID: f6de77eb2e44
Revises: 1f2b8ae492b8
Create Date: 2025-09-10 13:45:29.291663

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f6de77eb2e44'
down_revision: Union[str, Sequence[str], None] = 'dbc9b50dd47a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        "INSERT INTO system_version (version, description) VALUES ('1.0.0', 'Initial system version');"
    )
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
