#!/bin/bash

# This script correctly initializes the current directory ('talent-ai-microservices')
# as a new Git repository and pushes it for the first time to your
# personal private repository on GitHub.

# Exit immediately if a command exits with a non-zero status.
set -e

# --- Configuration ---
# The confirmed SSH URL for your NEW PRIVATE repository.
NEW_PERSONAL_REPO_URL="git@github.com:tech-lead/talent-ai-microservices-management.git"


# --- Script Execution ---
LOG_FILE="parent_repo_initialization_log_$(date +%Y-%m-%d_%H-%M-%S).txt"

# Redirect all output to the console and a log file
exec &> >(tee -a "$LOG_FILE")

echo "--- Starting Parent Repository Initialization ---"
echo "This will create a new Git repository here and link it to your private remote."
echo "Destination: $NEW_PERSONAL_REPO_URL"
echo "A detailed log will be saved to: $LOG_FILE"
echo ""

# --- Sanity Check ---
if [ -d ".git" ]; then
    echo "ERROR: This directory is already a Git repository. Aborting to prevent issues."
    echo "If you need to change the remote, please use the 'migrate_parent_repo.sh' script."
    exit 1
fi

# Step 1: Initialize a new Git repository
echo "Step 1: Initializing a new Git repository..."
git init
git branch -m main  # Set the default branch name to 'main'
echo "SUCCESS: Repository initialized."
echo ""

# Step 2: Create a .gitignore file to exclude logs
echo "Step 2: Creating a .gitignore file..."
# Using 'cat << EOF' to create a multi-line file
cat << EOF > .gitignore
# Log files and text files generated by scripts
*.log
*.txt
EOF
echo "SUCCESS: .gitignore created."
echo ""

# Step 3: Add all files for the first commit
echo "Step 3: Staging all files..."
# This will add the .gitignore, all scripts, and all service subdirectories
git add .
echo "SUCCESS: All files staged."
echo ""

# Step 4: Create the first commit
echo "Step 4: Creating the initial commit..."
git commit -m "feat: Initial commit of the microservices management structure"
echo "SUCCESS: Initial commit created."
echo ""

# Step 5: Add the remote location
echo "Step 5: Adding remote 'origin'..."
git remote add origin "$NEW_PERSONAL_REPO_URL"
echo "SUCCESS: Remote 'origin' linked to your private repository."
echo ""

# Step 6: Push to the new remote
echo "Step 6: Pushing to the new private repository..."
# '-u' sets the upstream branch so future 'git push' commands are simpler
git push -u origin main
echo "SUCCESS: Push to remote repository complete."
echo ""

echo "-----------------------------------------------------"
echo "--- Initialization and First Push Complete! ---"
echo "Your management repository is now live on your private GitHub account."
