/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */


export interface paths {
  "/health": {
    /**
     * Health Check
     * @description Get gateway and service health status.
     *
     * Returns overall status and per-service details for status bar.
     */
    get: operations["health_check_health_get"];
  };
  "/api/v1/system/status": {
    /**
     * System Status
     * @description Get comprehensive system status.
     */
    get: operations["system_status_api_v1_system_status_get"];
  };
  "/api/v1/services": {
    /**
     * List Services
     * @description List all 14 registered OpenTalent microservices.
     *
     * Returns registry with URLs and current status for each service.
     */
    get: operations["list_services_api_v1_services_get"];
  };
  "/api/v1/models": {
    /**
     * List Models
     * @description List all available models from all sources.
     *
     * Merges models from granite-interview-service and ollama.
     * Returns fallback if backends unavailable.
     */
    get: operations["list_models_api_v1_models_get"];
  };
  "/api/v1/models/select": {
    /**
     * Select Model
     * @description Select a specific model for interviews.
     *
     * Validates model exists in available models.
     */
    post: operations["select_model_api_v1_models_select_post"];
  };
  "/api/v1/voice/synthesize": {
    /**
     * Synthesize Speech
     * @description Proxy text-to-speech to voice-service when enabled.
     */
    post: operations["synthesize_speech_api_v1_voice_synthesize_post"];
  };
  "/api/v1/analytics/sentiment": {
    /**
     * Analyze Sentiment
     * @description Proxy sentiment analysis to analytics-service when enabled.
     */
    post: operations["analyze_sentiment_api_v1_analytics_sentiment_post"];
  };
  "/api/v1/agents/execute": {
    /**
     * Execute Agent
     * @description Proxy agent execution to agents-service when enabled.
     */
    post: operations["execute_agent_api_v1_agents_execute_post"];
  };
  "/api/v1/interviews/start": {
    /**
     * Start Interview
     * @description Start a new interview session.
     *
     * Routes to granite-interview-service if available, otherwise uses fallback templates.
     */
    post: operations["start_interview_api_v1_interviews_start_post"];
  };
  "/api/v1/interviews/respond": {
    /**
     * Respond To Interview
     * @description Submit candidate response and get next question.
     *
     * Continues interview flow with next question or marks complete if all questions done.
     */
    post: operations["respond_to_interview_api_v1_interviews_respond_post"];
  };
  "/api/v1/interviews/summary": {
    /**
     * Get Interview Summary
     * @description Get interview summary and assessment.
     *
     * Returns simple summary with question count and candidate info.
     */
    post: operations["get_interview_summary_api_v1_interviews_summary_post"];
  };
  "/api/v1/dashboard": {
    /**
     * Get Dashboard
     * @description Get complete dashboard data in one request.
     *
     * Combines health, models, and system info for UI.
     */
    get: operations["get_dashboard_api_v1_dashboard_get"];
  };
  "/": {
    /**
     * Root
     * @description Root endpoint with API info.
     */
    get: operations["root__get"];
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    /**
     * AnalyzeSentimentRequest
     * @description Request to analyze sentiment of text.
     */
    AnalyzeSentimentRequest: {
      /**
       * Text
       * @description Text to analyze
       */
      text: string;
      /**
       * Context
       * @description Context for analysis (e.g., 'interview_response', 'general')
       */
      context?: string | null;
    };
    /**
     * AnalyzeSentimentResponse
     * @description Response with sentiment analysis.
     */
    AnalyzeSentimentResponse: {
      /** @description Sentiment analysis */
      sentiment: components["schemas"]["SentimentScore"];
      /**
       * Text
       * @description Text that was analyzed
       */
      text: string;
      /**
       * Context
       * @description Analysis context
       */
      context?: string | null;
      /**
       * Sentences
       * @description Per-sentence analysis
       */
      sentences?: Record<string, never>[] | null;
    };
    /** HTTPValidationError */
    HTTPValidationError: {
      /** Detail */
      detail?: components["schemas"]["ValidationError"][];
    };
    /**
     * HealthResponse
     * @description Health check response.
     */
    HealthResponse: {
      /** Status */
      status: string;
      /**
       * Timestamp
       * Format: date-time
       */
      timestamp: string;
      /** Services */
      services: Record<string, never>;
      /** Summary */
      summary: Record<string, never>;
    };
    /**
     * InterviewConfig
     * @description Interview configuration.
     */
    InterviewConfig: {
      /**
       * Role
       * @description Interview role
       */
      role: string;
      /**
       * Model
       * @description Model to use
       */
      model: string;
      /**
       * Totalquestions
       * @description Total questions in interview
       * @default 5
       */
      totalQuestions?: number;
    };
    /**
     * InterviewResponseRequest
     * @description Request to respond to interview question.
     */
    InterviewResponseRequest: {
      /**
       * Sessionid
       * @description Session ID (optional)
       */
      sessionId?: string | null;
      /**
       * Message
       * @description User's response message
       */
      message: string;
      /** @description Full session (client can send entire session) */
      session?: components["schemas"]["InterviewSession"] | null;
    };
    /**
     * InterviewSession
     * @description Interview session data matching desktop app contract.
     */
    InterviewSession: {
      config: components["schemas"]["InterviewConfig"];
      /** Messages */
      messages: components["schemas"]["Message"][];
      /** Currentquestion */
      currentQuestion: number;
      /** Iscomplete */
      isComplete: boolean;
    };
    /**
     * Message
     * @description Message in interview conversation.
     */
    Message: {
      /**
       * Role
       * @description Message role: system, user, or assistant
       */
      role: string;
      /**
       * Content
       * @description Message content
       */
      content: string;
    };
    /**
     * ModelInfo
     * @description Model information.
     */
    ModelInfo: {
      /**
       * Id
       * @description Model ID
       */
      id: string;
      /**
       * Name
       * @description Human-readable name
       */
      name: string;
      /**
       * Paramcount
       * @description Parameter count (350M, 2B, 8B, etc.)
       */
      paramCount: string;
      /**
       * Ramrequired
       * @description RAM required
       */
      ramRequired: string;
      /**
       * Downloadsize
       * @description Download size
       */
      downloadSize: string;
      /**
       * Description
       * @description Model description
       */
      description: string;
      /**
       * Dataset
       * @description Training dataset
       */
      dataset?: string | null;
      /**
       * Source
       * @description Model source
       */
      source?: string | null;
    };
    /**
     * ModelsResponse
     * @description Response with list of models.
     */
    ModelsResponse: {
      /** Models */
      models: components["schemas"]["ModelInfo"][];
    };
    /**
     * SentimentScore
     * @description Sentiment analysis result.
     */
    SentimentScore: {
      /**
       * Score
       * @description Sentiment score (-1.0 to 1.0)
       */
      score: number;
      /**
       * Magnitude
       * @description Sentiment magnitude (0.0 to 1.0)
       */
      magnitude: number;
      /**
       * Label
       * @description Sentiment label (positive, negative, neutral)
       */
      label: string;
    };
    /**
     * StartInterviewRequest
     * @description Request to start an interview.
     */
    StartInterviewRequest: {
      /**
       * Role
       * @description Interview role (Software Engineer, Product Manager, Data Analyst)
       */
      role: string;
      /**
       * Model
       * @description Model to use
       * @default vetta-granite-2b-gguf-v4
       */
      model?: string;
      /**
       * Totalquestions
       * @description Total questions
       * @default 5
       */
      totalQuestions?: number;
    };
    /**
     * SynthesizeSpeechRequest
     * @description Request to synthesize speech from text.
     */
    SynthesizeSpeechRequest: {
      /**
       * Text
       * @description Text to synthesize
       */
      text: string;
      /**
       * Voice
       * @description Voice identifier (e.g., en-US-Neural2-C, en-GB-Neural2-A)
       * @default en-US-Neural2-C
       */
      voice?: string;
      /**
       * Speed
       * @description Speech speed (0.5-2.0)
       * @default 1
       */
      speed?: number;
      /**
       * Pitch
       * @description Pitch adjustment (-20 to 20)
       * @default 0
       */
      pitch?: number;
    };
    /**
     * SynthesizeSpeechResponse
     * @description Response with synthesized audio.
     */
    SynthesizeSpeechResponse: {
      /**
       * Audiourl
       * @description URL to audio file
       */
      audioUrl?: string | null;
      /**
       * Audiobase64
       * @description Base64-encoded audio
       */
      audioBase64?: string | null;
      /**
       * Duration
       * @description Audio duration in seconds
       */
      duration?: number | null;
      /**
       * Format
       * @description Audio format (mp3, wav, ogg)
       * @default mp3
       */
      format?: string;
      /**
       * Text
       * @description Text that was synthesized
       */
      text: string;
      /**
       * Voice
       * @description Voice used
       */
      voice: string;
    };
    /** ValidationError */
    ValidationError: {
      /** Location */
      loc: (string | number)[];
      /** Message */
      msg: string;
      /** Error Type */
      type: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type $defs = Record<string, never>;

export type external = Record<string, never>;

export interface operations {

  /**
   * Health Check
   * @description Get gateway and service health status.
   *
   * Returns overall status and per-service details for status bar.
   */
  health_check_health_get: {
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["HealthResponse"];
        };
      };
    };
  };
  /**
   * System Status
   * @description Get comprehensive system status.
   */
  system_status_api_v1_system_status_get: {
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": Record<string, never>;
        };
      };
    };
  };
  /**
   * List Services
   * @description List all 14 registered OpenTalent microservices.
   *
   * Returns registry with URLs and current status for each service.
   */
  list_services_api_v1_services_get: {
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": Record<string, never>;
        };
      };
    };
  };
  /**
   * List Models
   * @description List all available models from all sources.
   *
   * Merges models from granite-interview-service and ollama.
   * Returns fallback if backends unavailable.
   */
  list_models_api_v1_models_get: {
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["ModelsResponse"];
        };
      };
    };
  };
  /**
   * Select Model
   * @description Select a specific model for interviews.
   *
   * Validates model exists in available models.
   */
  select_model_api_v1_models_select_post: {
    parameters: {
      query: {
        model_id: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": Record<string, never>;
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Synthesize Speech
   * @description Proxy text-to-speech to voice-service when enabled.
   */
  synthesize_speech_api_v1_voice_synthesize_post: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["SynthesizeSpeechRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["SynthesizeSpeechResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Analyze Sentiment
   * @description Proxy sentiment analysis to analytics-service when enabled.
   */
  analyze_sentiment_api_v1_analytics_sentiment_post: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["AnalyzeSentimentRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["AnalyzeSentimentResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Execute Agent
   * @description Proxy agent execution to agents-service when enabled.
   */
  execute_agent_api_v1_agents_execute_post: {
    requestBody: {
      content: {
        "application/json": Record<string, never>;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": Record<string, never>;
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Start Interview
   * @description Start a new interview session.
   *
   * Routes to granite-interview-service if available, otherwise uses fallback templates.
   */
  start_interview_api_v1_interviews_start_post: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["StartInterviewRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["InterviewSession"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Respond To Interview
   * @description Submit candidate response and get next question.
   *
   * Continues interview flow with next question or marks complete if all questions done.
   */
  respond_to_interview_api_v1_interviews_respond_post: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["InterviewResponseRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["InterviewSession"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Get Interview Summary
   * @description Get interview summary and assessment.
   *
   * Returns simple summary with question count and candidate info.
   */
  get_interview_summary_api_v1_interviews_summary_post: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["InterviewSession"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": Record<string, never>;
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Get Dashboard
   * @description Get complete dashboard data in one request.
   *
   * Combines health, models, and system info for UI.
   */
  get_dashboard_api_v1_dashboard_get: {
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": Record<string, never>;
        };
      };
    };
  };
  /**
   * Root
   * @description Root endpoint with API info.
   */
  root__get: {
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": Record<string, never>;
        };
      };
    };
  };
}
